aws_region="eu-west-1"
stack="solucions-cloud-automation-test"
fargate-task-service-role="solucions-cloud-automation-test-role"
aws_ecr="petclinic"
aws_profile="default"
source_repo_name="petclinic"
source_repo_branch="master"
image_repo_name="petclinic"