on:
  push:
    branches: [master]
    paths: [ 'petclinic/**' ]
  pull_request:
    branches: [master]
    paths: [ 'petclinic/**' ]

jobs:
  build:
    name: Execute AWS CodePipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        if: github.ref == 'refs/heads/main'
        with:
          aws-region: "eu-west-1"
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          pipeline-name: "petclinic-main-Pipeline"